apiVersion: v1
kind: Secret
metadata:
  name: restaurantflow-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  rabbitmq-username: {{ .Values.rabbitmq.username | quote }}
  rabbitmq-password: {{ .Values.rabbitmq.password | quote }}
  postgres-password: {{ .Values.postgres.password | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: restaurantflow-config
  namespace: {{ .Release.Namespace }}
data:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_HTTP_PORTS: "8080"
  RabbitMq__Host: rabbitmq

