{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: restaurantflow
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: {{ .Values.externalSecrets.secretStoreKind }}
  target:
    name: {{ include "restaurantflow.secretName" . }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.externalSecrets.remoteKey }}
{{- end }}
