apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes: [Ingress]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gateway-ingress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels: { app.kubernetes.io/name: gateway }
  policyTypes: [Ingress]
  ingress:
    - ports: [{ protocol: TCP, port: 8080 }]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: api-ingress-from-gateway
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values: [menu-api, orders-api, kitchen-api, payments-api]
  policyTypes: [Ingress]
  ingress:
    - from:
        - podSelector:
            matchLabels: { app.kubernetes.io/name: gateway }
      ports: [{ protocol: TCP, port: 8080 }]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: menu-internal-from-orders
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels: { app.kubernetes.io/name: menu-api }
  policyTypes: [Ingress]
  ingress:
    - from:
        - podSelector:
            matchLabels: { app.kubernetes.io/name: orders-api }
      ports: [{ protocol: TCP, port: 8080 }]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: broker-ingress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels: { app.kubernetes.io/name: rabbitmq }
  policyTypes: [Ingress]
  ingress:
    - from:
        - podSelector:
            matchExpressions:
              - key: app.kubernetes.io/part-of
                operator: In
                values: [restaurantflow]
      ports: [{ protocol: TCP, port: 5672 }]
---
{{- range $database := list "menu" "orders" "kitchen" "payments" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $database }}-database-ingress
  namespace: {{ $.Release.Namespace }}
spec:
  podSelector:
    matchLabels: { app.kubernetes.io/name: {{ $database }}-db }
  policyTypes: [Ingress]
  ingress:
    - from:
        - podSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values: [{{ $database }}-api, {{ $database }}-api-migrations]
      ports: [{ protocol: TCP, port: 5432 }]
---
{{- end }}
